name: continuous integration

on:
  push:
    branches:
      - main
    tags:
      - v0.*
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
