name: continuous integration

on:
  push:
    branches:
      - main
    tags:
      - v0.*
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: cachix/install-nix-action@v30

      - run: npm clean-install
      - run: npm test
        env:
          CI: true
      - run: npm run build

      - run: nix build .#default

      - run: npm pack
        if: startsWith(github.ref, 'refs/tags/')
      - uses: softprops/action-gh-release@v2
        with:
          files: hippocampusgirl-upload-*.tgz
        if: startsWith(github.ref, 'refs/tags/')
